pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    druid:
      url:  jdbc:postgresql://10.15.1.26:30205/resource_catalog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name:  org.postgresql.Driver
      username:  postgres
      password:  DcP@ssw0rd123
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM sys_user
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  rabbitmq:
    host: 192.168.0.123
    port: 5672
    username: mscx
    password: mscx
    virtual-host: /
    # p端收到回调，确认消息发送结果
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答方式
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 10 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试

templatepath: /data/resourcecatalog/templates/
