spring:
  profiles:
    active: db
  messages:
    encoding: UTF-8

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  DEBUG
    com.digitalchina.resourcecatalog.db:  DEBUG